### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by matte0080** [escomputers/BASD#46]
I mate, 

thank you for you great job, it's really usefully!  

I have a MacOs , i think will could be great if you create dockerized version. In this mode, it will works in every os :)

**Comment by escomputers** [comment]
Did you try installing Parallels and running BASD from there?
Anyway web branch has been created!

**Comment by matte0080** [comment]
Grande! =) 

Is web branch ready for usage?

**Comment by escomputers** [comment]
Not yet, it requires a bit of work to be done,  when README.md will be updated and this issue closed, you can be sure that web version is ready for production. Otherwise you can just hit the button "Watch" to be always updated with latest repo news.
Here's UI preview
![Capture](https://user-images.githubusercontent.com/4378005/203936337-1c7d38cc-e903-4409-bd38-0a9e65d8af59.JPG)

**Comment by escomputers** [comment]
Implemented with 15e156237e226920a63d49d17ff018605b641adf
